- .travis.yml
- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_app/version.py
- setup.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> release: v1.0.0a1

- .editorconfig
- docs/configuration.rst
- invenio_app/__init__.py
- invenio_app/config.py
- invenio_app/ext.py
- requirements-devel.txt
- setup.py
- tests/conftest.py
- tests/test_app.py
- tests/test_wsgi.py
* Adds the flask-limiter and secure headers. (closes #6)
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> global: move flask-limiter and secure headers

- setup.py
- Added a dependency to flask-shell-ipython
(closes #115)
> installation: include flask-shell-ipython

- invenio_app/config.py
* Enhances Talisman documentation.
(closes inveniosoftware/invenio-app-ils#18)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> config: enhance Talisman documentation

- invenio_app/config.py
- invenio_app/factory.py
- pytest.ini
- requirements-devel.txt
- run-tests.sh
- setup.py
- tests/test_factory.py
* Adds Jinja byte code caching. (closes #2)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> factory: Jinja byte code caching support addition

- AUTHORS.rst
- CHANGES.rst
- invenio_app/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> release: v1.0.2

- invenio_app/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> version: post-release bump

- invenio_app/ext.py
- tests/test_app.py
> config: fix default value of CSP header

- CHANGES.rst
- invenio_app/version.py
> release: v.1.0.5

- .travis.yml
- setup.py
* Pins pytest <5.0.0 due to incompatibility with Python 2.7.
> tests: pin pytest <5.0

- docs/api.rst
- invenio_app/config.py
- invenio_app/ext.py
- invenio_app/helpers.py
- invenio_app/limiter.py
- setup.py
- tests/conftest.py
- tests/test_app.py
- tests/test_factory.py
- tests/test_limiter.py
> global: add default key function for flask limiter

- CHANGES.rst
- invenio_app/factory.py
- invenio_app/limiter.py
- invenio_app/version.py
- setup.py
- tests/conftest.py
* fixes global variable issue of instance_path and static folder
* addresses (/inveniosoftware/pytest-invenio/issues/17)
to be merged after https://github.com/inveniosoftware/invenio-base/pull/142
> factory: fix instance_path and static_folder evaluation

- invenio_app/ext.py
- tests/test_app.py
> ext: exempt ping view from rate limiting

- invenio_app/helpers.py
- setup.py
- tests/conftest.py
- tests/test_helpers.py
> helpers: add "get_safe_redirect_target"

- invenio_app/version.py
- setup.py
Closes https://github.com/inveniosoftware/invenio-app/issues/60
> dependencies: pin lower on flask-limiter due to breaking changes

- pytest.ini
- run-tests.sh
- tests/conftest.py
Addresses inveniosoftware/opensource#65
> Fixed Isort

- invenio_app/config.py
closes https://github.com/CERNDocumentServer/cds-ils/issues/150
> limiter: Increase limit rates

- invenio_app/config.py
:heart: Thank you for your contribution!
Closes https://github.com/zenodo/rdm-project/issues/656
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the …
> security: added default rate limits for endpoints

- invenio_app/config.py
:heart: Thank you for your contribution!
Closes https://github.com/zenodo/rdm-project/issues/656
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the …
> config: updated rate limit for password

- CHANGES.rst
- invenio_app/__init__.py
Will just merge and release this when tests pass.
> :package: release: v2.1.0
